---
title: "Final Project"
subtitle: NBA data
author: Aidan and Liam Greenlee
output:
  slidy_presentation: default
  beamer_presentation: default
---

## R Markdown

```{r markdown, include=FALSE}
library(tidyverse)
require(gridExtra)
library(tidymodels)
library(dplyr)
library(e1071)
library(modelr)
library(caret)
library(lubridate)
library(tree)
library(glmnet)
```

## Preparing Data

```{r prep, echo=FALSE}
data1 <- na.omit(read.csv(file = "shot_logs.csv"))
#unique <- unique(data1$player_name)
#filter(data1, player_name == "brian roberts")
#plot1 <- ggplot(data1,mapping = aes(x=SHOT_DIST,y=CLOSE_DEF_DIST,color = SHOT_RESULT)) + geom_point()
#plot2 <- ggplot(data1,mapping = aes(x=SHOT_DIST,y=CLOSE_DEF_DIST,color = PTS_TYPE)) + geom_point()
#grid.arrange(plot1, plot2, ncol=2)
data1$GAME_CLOCK<- as.double(ms(data1$GAME_CLOCK))
data1 <- data1 %>% mutate(SHOT_RESULT = ifelse(SHOT_RESULT == "made", 1, 0))
#data <- data.frame(data1$LOCATION, data1$W, data1$FINAL_MARGIN, data1$SHOT_NUMBER, data1$PERIOD, data1$GAME_CLOCK, data1$SHOT_CLOCK, data1$DRIBBLES, data1$TOUCH_TIME, data1$SHOT_DIST, data1$PTS_TYPE, data1$CLOSEST_DEFENDER_PLAYER_ID, data1$CLOSE_DEF_DIST, data1$player_id, GAME_ID)
data <- data1[,c(1,3,4,5,6,7,8,9,10,11,12,13,14,16,17,21)]
data$GAME_CLOCK_TOT <- data$GAME_CLOCK+(data$PERIOD-1)*720
```
## Splitting Data

```{r split, results='hide'}
set.seed(5040)
resample <- initial_split(prop = .7, data)
test <- testing(resample)
train <- training(resample)
split <- resample_partition(train, c(train1 = .1, train2 = .9))
train1 <- as_tibble(split$train1)
train2 <- as_tibble(split$train2)
train1
```

## Graph

```{r graph, echo=FALSE}
plot(x = train1$GAME_CLOCK, y = train1$PERIOD)
```

## Fit Data

```{r}
x <- model.matrix(SHOT_RESULT ~ ., train)
y <- train$SHOT_RESULT
nfolds <- 40
foldid <- sample(1:nfolds, length(y), replace = TRUE)
do_cv <- function(alpha) {
  result <- cv.glmnet(x, y, alpha = alpha, nfolds = nfolds, foldid = foldid)
  tibble(alpha = alpha, lambda = result$lambda.min, cv = min(result$cvm))
}
g <- seq(0, 1, 0.1) %>% map_dfr(do_cv) %>% mutate(rank = row_number(cv))
g
alpha <- grep("^1$", g$rank)*.1-.1
lambdamin <- g$lambda[which.min(g$cv)]
#lambdamin <- cv.glmnet(x, y, alpha = alpha, nfolds = nfolds)$lambda.min
elasticnet <- glmnet(x, y, alpha = alpha, lambda = lambdamin)
vars <- elasticnet$beta %>% as.matrix() %>% as_tibble(rownames = "variable")
arrange(vars, desc((vars$s0)^2))
```

```{r}
enet <- glmnet(x, y, alpha = alpha)
plot(enet, xvar= "lambda")
```
```{r}
elasticnet
enetpred <- as_tibble(predict(elasticnet, newx=model.matrix(SHOT_RESULT ~ ., data = test)))
enetpred
enetpred <- enetpred %>% mutate(s0 = ifelse(s0 >= .5, 1, 0))
enetpred
```


```{r fit, echo=FALSE}
svmfit <- svm(SHOT_RESULT ~ LOCATION + W + FINAL_MARGIN + SHOT_NUMBER + PERIOD + GAME_CLOCK + SHOT_CLOCK + DRIBBLES + TOUCH_TIME + SHOT_DIST + PTS_TYPE + CLOSEST_DEFENDER_PLAYER_ID + CLOSE_DEF_DIST + player_id + GAME_ID + GAME_CLOCK_TOT, data = train1, kernel = "radial", cost = 10, gamma = 1)

lmfit <- lm( data = train1, SHOT_RESULT ~ LOCATION + W + FINAL_MARGIN + SHOT_NUMBER + PERIOD + GAME_CLOCK + SHOT_CLOCK + DRIBBLES + TOUCH_TIME + SHOT_DIST + PTS_TYPE + CLOSEST_DEFENDER_PLAYER_ID + CLOSE_DEF_DIST + player_id + GAME_ID + GAME_CLOCK_TOT)

treefit <- tree( data = train1, formula = SHOT_RESULT ~ LOCATION + W + FINAL_MARGIN + SHOT_NUMBER + PERIOD + GAME_CLOCK + SHOT_CLOCK + DRIBBLES + TOUCH_TIME + SHOT_DIST + PTS_TYPE + CLOSEST_DEFENDER_PLAYER_ID + CLOSE_DEF_DIST + player_id + GAME_ID + GAME_CLOCK_TOT)
cvtree <- cv.tree(treefit, FUN = prune.tree, K = 10)
```

```{r}
svmfit
test$svmfit <- predict(svmfit, test)
test$lmfit <- predict(lmfit, test)
cvtree
```
## MSEs and Predictions

```{r mse, echo=FALSE}
library(caret)
varImp(lmfit)
treefit
plot(treefit)
text(treefit, pretty = 1, all = TRUE)
test$treefit <- predict(treefit, test)
test <- test %>% mutate(treefit = ifelse(treefit >= .5, 1, 0))
test <- test %>% mutate(lmfit = ifelse(lmfit >= .5, 1, 0))
test <- test %>% mutate(svmfit = ifelse(svmfit >= .5, 1, 0))
cat("after\n")
mean((test$treefit - test$SHOT_RESULT)^2)
mean((test$lmfit - test$SHOT_RESULT)^2)
mean((test$svmfit - test$SHOT_RESULT)^2)
```

